services:
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: michael
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  maildev:
    container_name: maildev
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - postgres
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - postgres
    restart: unless-stopped

#  eureka-server:
#    image: michaelroyf87/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#
#  apigw:
#    image: michaelroyf87/apigw:latest
#    container_name: apigw
#    ports:
#      - "9191:9191"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - eureka-server
#
#  config-server:
#    image: michaelroyf87/config-server:latest
#    container_name: config-server
#    ports:
#      - "8888:8888"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#    depends_on:
#      - eureka-server
#
#  employee-service:
#    image: michaelroyf87/employee-service:latest
#    container_name: employee-service
#    ports:
#      - "8090:8090"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - eureka-server
#      - config-server
#

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge


volumes:
  postgres:
  pgadmin: